services:
  - type: web
    name: whatsapp-email-forwarder
    env: node
    buildCommand: |
      npm install --legacy-peer-deps
      npm install puppeteer@21.5.0 --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SENDER_TO_WATCH
        sync: false
      - key: WHATSAPP_RECIPIENT
        sync: false
    healthCheckPath: /
    autoDeploy: true 